services:
  nodejs:
    build:
      context: .
      dockerfile: docker/nodejs/Dockerfile
    container_name: laravel_nodejs
    working_dir: /var/www/html
    volumes:
      - ./www:/var/www/
    ports:
      - "5173:5173"
    command: ["sleep", "infinity"]

  golang:
    image: golang:1.24-alpine
    working_dir: /var/www/golang-api
    volumes:
      - ./golang-api:/var/www/golang-api
    ports:
      - "8081:8080"
    command: ["sleep", "infinity"]
